# Copyright 2026 Ângelo Coelho. All rights reserved.
# PROPRIETARY — NON-COMMERCIAL USE ONLY.
# Licensed under PolyForm Noncommercial License 1.0.0.
# See LICENSE and https://angelorscoelho.dev for licensing.
#

"""
Siemens Energy — Gas Turbine Maintenance History API
Lambda handler: /maintenance-history  (GET)

Returns structured maintenance history records for a given equipment asset.
Records are hardcoded to simulate retrieval from a database (DynamoDB / RDS).
In production, replace the HISTORY dictionary with a DynamoDB scan/query.

The records are also contributed to the RAG context window so the AI assistant
can answer questions such as "What are the most common failure patterns for this
turbine?" or "When was the last major overhaul performed?".
"""

import json
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)

# ── Maintenance History Knowledge Base ────────────────────────────────────────
# 6-10 records per asset, ordered newest first.
# Each record:
#   timestamp      – ISO-8601 UTC string
#   orderNumber    – work order reference
#   type           – maintenance category
#   technician     – person / team responsible
#   description    – what was performed
#   findings       – what was found
#   partsReplaced  – list of parts (may be empty)
#   durationHours  – duration of the work in hours
#   result         – COMPLETED | COMPLETED_WITH_FINDINGS | DEFERRED
#   hoursAtService – turbine operating hours at time of service

HISTORY = {
    "GT-01": [
        {"timestamp": "2025-12-10T07:00:00Z", "orderNumber": "WO-2025-GT01-007", "type": "Hot Gas Path Inspection", "technician": "Team Alpha — J. Müller (lead)", "description": "Scheduled HGP inspection at 8,000 EOH. Combustion liners, transition pieces, and first-stage nozzles inspected. All components within acceptance limits. Thermal barrier coatings intact. Unit returned to service.", "findings": "Minor erosion on blade leading edges — within acceptance criteria. TBC thickness nominal across all blades.", "partsReplaced": ["Combustion liner gaskets (×16)", "Turbine shroud seal strips (×4)"], "durationHours": 144, "result": "COMPLETED", "hoursAtService": 8000},
        {"timestamp": "2025-06-15T06:00:00Z", "orderNumber": "WO-2025-GT01-006", "type": "Compressor Offline Water Wash", "technician": "J. Schmidt", "description": "Offline water wash performed due to compressor efficiency drop of 1.2%. Post-wash efficiency recovered to design baseline.", "findings": "Salt deposit buildup on compressor blades stages 1–5. Post-wash efficiency gain: +1.8%.", "partsReplaced": [], "durationHours": 8, "result": "COMPLETED", "hoursAtService": 7200},
        {"timestamp": "2024-12-02T08:00:00Z", "orderNumber": "WO-2024-GT01-005", "type": "Combustion Inspection", "technician": "Team Beta — K. Wagner", "description": "Scheduled CI at 4,000 EOH. Fuel nozzles cleaned, cross-fire tubes inspected, liner wear measured. All within 20% wear limit.", "findings": "Fuel nozzle carbon deposit moderate. Liner wear at 11% — acceptable. All cross-fire tubes operational.", "partsReplaced": ["Fuel nozzle tip inserts (×16)", "Combustion can gaskets (×16)"], "durationHours": 72, "result": "COMPLETED", "hoursAtService": 4000},
        {"timestamp": "2024-05-20T10:00:00Z", "orderNumber": "WO-2024-GT01-004", "type": "Lube Oil Analysis & Change", "technician": "M. Fischer", "description": "Annual lube oil change and system inspection per Section 15 of maintenance manual.", "findings": "Viscosity 31.2 cSt within ISO VG 32 spec. Acid number nominal. No metal contamination detected.", "partsReplaced": ["ISO VG 32 turbine oil (×600 L)", "Oil filter cartridges (×3)"], "durationHours": 12, "result": "COMPLETED", "hoursAtService": 3100},
        {"timestamp": "2023-11-10T07:30:00Z", "orderNumber": "WO-2023-GT01-003", "type": "Inlet Filter Replacement", "technician": "F. Braun", "description": "Stage 1 and Stage 2 inlet filter elements replaced. ΔP across filter bank approached 25 mbar threshold.", "findings": "Filter ΔP reached 23.4 mbar — preventive replacement carried out.", "partsReplaced": ["Stage 1 filter elements (×24)", "Stage 2 HEPA filters (×12)"], "durationHours": 6, "result": "COMPLETED", "hoursAtService": 1800},
        {"timestamp": "2023-06-01T06:00:00Z", "orderNumber": "WO-2023-GT01-002", "type": "Commissioning & Initial Inspection", "technician": "Siemens Energy Commissioning Team", "description": "Unit commissioning completed. First fire achieved, load ramp-up to 100% rated power. Documentation complete.", "findings": "No issues found during commissioning. All parameters within design envelope. Unit accepted for commercial operation.", "partsReplaced": [], "durationHours": 240, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "ST-01": [
        {"timestamp": "2026-03-10T14:32:00Z", "orderNumber": "WO-2026-ST01-010", "type": "Emergency Bearing Inspection", "technician": "On-call Team — R. Johnson", "description": "UNPLANNED: Bearing #3 vibration alarm triggered at 4.5 mm/s. Emergency inspection initiated. Unit kept at reduced load (70%).", "findings": "Bearing #3 shows oil film breakdown — elevated metal particles in oil sample. Vibration trend upward over 72 h. Bearing replacement recommended within 48 h.", "partsReplaced": ["Lube oil sample (analysis pending)"], "durationHours": 4, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 23810},
        {"timestamp": "2025-11-15T08:00:00Z", "orderNumber": "WO-2025-ST01-009", "type": "Combustion Inspection", "technician": "Team Gamma — P. Davis", "description": "Combustion inspection at 22,000 EOH. Fuel nozzles cleaned, cross-fire tubes inspected. Liner wear at 17% — approaching replacement limit.", "findings": "Liner wear 17% — within 20% limit but trending toward replacement at next CI.", "partsReplaced": ["Fuel nozzle tip inserts (×12)", "Cross-fire tubes (×2)"], "durationHours": 64, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 22000},
        {"timestamp": "2025-04-20T07:00:00Z", "orderNumber": "WO-2025-ST01-008", "type": "Hot Gas Path Inspection", "technician": "Team Alpha — B. Carter", "description": "HGP inspection at 20,000 EOH. First-stage blades showing significant thermal fatigue. TBC partially spalled on 3 blades.", "findings": "Stage 1 blade TBC spallation on blades #4, #7, #11. Creep elongation within limits. Transition pieces oxidized — replaced.", "partsReplaced": ["Stage 1 transition pieces (×12)", "Combustion liner segments (×6)", "Thermocouple probes (×4)"], "durationHours": 192, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 20000},
        {"timestamp": "2024-01-15T06:00:00Z", "orderNumber": "WO-2024-ST01-007", "type": "Major Overhaul", "technician": "Siemens Energy MRO Team", "description": "Major overhaul at 18,000 EOH. Full hot-section disassembly, blade row 1 replacement, compressor wash, all seals renewed.", "findings": "Blade row 1 at end-of-life — replaced as planned. Bearing #2 and #4 replaced preventively. Rotor balance within ISO 2.5.", "partsReplaced": ["Blade row 1 complete set (×36)", "Bearings #2 and #4", "All combustion liners", "Compressor stage 1–3 blades"], "durationHours": 480, "result": "COMPLETED", "hoursAtService": 18000},
        {"timestamp": "2022-09-10T08:00:00Z", "orderNumber": "WO-2022-ST01-005", "type": "Hot Gas Path Inspection", "technician": "Team Beta", "description": "HGP inspection at 12,000 EOH. Blades and nozzles in acceptable condition. Combustion liners replaced as scheduled.", "findings": "All blades within creep limits. Stage 1 nozzles show 18% wear — below 25% limit. Liners replaced at scheduled interval.", "partsReplaced": ["All combustion liners (×12)", "Stage 1 nozzle seals"], "durationHours": 168, "result": "COMPLETED", "hoursAtService": 12000},
        {"timestamp": "2021-09-05T07:00:00Z", "orderNumber": "WO-2021-ST01-004", "type": "Combustion Inspection", "technician": "T. Williams", "description": "CI at 8,000 EOH. Normal wear found. Fuel nozzles cleaned and reinstalled.", "findings": "All combustion components in good condition. No anomalies.", "partsReplaced": ["Fuel nozzle tip inserts (×12)"], "durationHours": 60, "result": "COMPLETED", "hoursAtService": 8000},
    ],
    "GT-02": [
        {"timestamp": "2026-01-15T08:00:00Z", "orderNumber": "WO-2026-GT02-006", "type": "Inlet Filter Replacement", "technician": "A. Al-Rashid", "description": "Stage 1 and 2 inlet filters replaced per schedule. Dusty desert conditions require accelerated replacement cycle.", "findings": "Filter loading heavier than expected — suggest reducing replacement interval to 1,200 EOH given local dust conditions.", "partsReplaced": ["Stage 1 coarse filters (×18)", "Stage 2 fine filters (×9)"], "durationHours": 6, "result": "COMPLETED", "hoursAtService": 5100},
        {"timestamp": "2025-08-10T06:00:00Z", "orderNumber": "WO-2025-GT02-005", "type": "Combustion Inspection", "technician": "Team Delta — H. Al-Zahrani", "description": "CI at 4,000 EOH. All combustion components within limits. Compressor wash carried out offline simultaneously.", "findings": "Combustion system in excellent condition. Compressor efficiency improved by 1.4% post-wash.", "partsReplaced": ["Combustion can O-rings (×18)", "Fuel nozzle strainers (×18)"], "durationHours": 80, "result": "COMPLETED", "hoursAtService": 4000},
        {"timestamp": "2025-02-20T08:00:00Z", "orderNumber": "WO-2025-GT02-004", "type": "Lube Oil Analysis & Change", "technician": "S. Hassan", "description": "Lube oil change at 2,000 h interval. High ambient temperature environment (45°C average).", "findings": "Oil oxidation index slightly elevated — within spec but trending. Recommend next change at 3,000 h given ambient conditions.", "partsReplaced": ["ISO VG 32 turbine oil (×180 L)", "Oil filter elements (×2)"], "durationHours": 8, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 2800},
        {"timestamp": "2024-09-12T07:00:00Z", "orderNumber": "WO-2024-GT02-003", "type": "Online Water Wash (×3)", "technician": "F. Al-Amri", "description": "Routine online compressor washes performed at 500-hour intervals. Compressor efficiency maintained.", "findings": "Efficiency trend stable. Dust ingestion controlled effectively by current filtration system.", "partsReplaced": [], "durationHours": 3, "result": "COMPLETED", "hoursAtService": 2400},
        {"timestamp": "2025-07-01T06:00:00Z", "orderNumber": "WO-2025-GT02-002", "type": "Borescope Inspection", "technician": "K. Nomura (Siemens)", "description": "Borescope inspection of compressor and hot section following filter clogging event.", "findings": "No ingestion damage found. Compressor blade condition good. Hot section nominal.", "partsReplaced": [], "durationHours": 16, "result": "COMPLETED", "hoursAtService": 4800},
        {"timestamp": "2025-07-15T06:00:00Z", "orderNumber": "WO-2025-GT02-001", "type": "Commissioning & Initial Inspection", "technician": "Siemens Energy Commissioning Team", "description": "Unit commissioned 2025-06-20. Dual-fuel system verified, DLE burners tuned. All emission limits met.", "findings": "Commissioning completed without issues. NOx 22 ppm. Unit operational.", "partsReplaced": [], "durationHours": 168, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "ST-02": [
        {"timestamp": "2025-09-01T07:00:00Z", "orderNumber": "WO-2025-ST02-007", "type": "Hot Section Inspection", "technician": "Team Omega — D. van der Berg", "description": "Hot section inspection at 12,000 EOH. Turbine blades checked for creep, erosion, and corrosion.", "findings": "Stage 1–3 blades within creep elongation limits. Erosion shields intact. Steam seals in good condition.", "partsReplaced": ["HP turbine sealing strips (×8)", "Journal bearing inserts (×2)"], "durationHours": 120, "result": "COMPLETED", "hoursAtService": 12000},
        {"timestamp": "2024-11-10T08:00:00Z", "orderNumber": "WO-2024-ST02-006", "type": "Steam System Inspection", "technician": "A. de Jong", "description": "Annual steam system inspection. Main and reheat stop valves serviced. Steam strainers cleaned.", "findings": "Main steam stop valve seat wear acceptable. Strainer mesh 15% blocked — cleaned. Condensate pump seals worn — replaced.", "partsReplaced": ["Condensate pump mechanical seals (×2)", "Steam strainer mesh (×4)"], "durationHours": 48, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 11000},
        {"timestamp": "2024-03-15T07:00:00Z", "orderNumber": "WO-2024-ST02-005", "type": "Lube Oil Change", "technician": "B. Janssen", "description": "Planned lube oil change and bearing inspection. All bearings within vibration and temperature limits.", "findings": "Oil analysis clean — no metal particles. Bearing vibrations 1.3–1.6 mm/s, all within limits.", "partsReplaced": ["Turbine oil ISO VG 46 (×400 L)", "Oil cooler gaskets"], "durationHours": 14, "result": "COMPLETED", "hoursAtService": 10200},
        {"timestamp": "2023-09-20T08:00:00Z", "orderNumber": "WO-2023-ST02-004", "type": "Governor & Control System", "technician": "Controls Team — E. Bakker", "description": "Annual calibration of turbine governor, speed sensors, and overspeed protection system.", "findings": "All control parameters within calibration limits. Overspeed trip set point confirmed at 110% rated speed.", "partsReplaced": ["Speed sensor O-rings (×4)"], "durationHours": 16, "result": "COMPLETED", "hoursAtService": 8500},
        {"timestamp": "2022-12-05T07:00:00Z", "orderNumber": "WO-2022-ST02-003", "type": "Planned Outage Inspection", "technician": "Team Delta", "description": "Annual planned outage inspection. Turbine casing flanges checked, LP blade row inspected, gland sealing system serviced.", "findings": "LP blade row in excellent condition. Gland seal strips worn on stage 4 — replaced.", "partsReplaced": ["LP stage 4 gland seal strips", "HP valve packing sets (×2)"], "durationHours": 96, "result": "COMPLETED", "hoursAtService": 6000},
    ],
    "GT-03": [
        {"timestamp": "2025-12-01T11:00:00Z", "orderNumber": "WO-2025-GT03-009", "type": "Unplanned: Combustion Liner Check", "technician": "Emergency Team — O. Adeyemi", "description": "UNPLANNED: Exhaust temperature trending 15°C above baseline over 30 days. Borescope inspection of combustion section performed.", "findings": "Fuel nozzle #3 and #5 showing carbon fouling. Combustion liner zone B showing localized hot spot. Nozzles cleaned; liner monitoring intensified.", "partsReplaced": ["Fuel nozzle tips #3 and #5"], "durationHours": 18, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 28900},
        {"timestamp": "2025-05-20T07:00:00Z", "orderNumber": "WO-2025-GT03-008", "type": "Hot Gas Path Inspection", "technician": "Team Epsilon — C. Okafor", "description": "HGP inspection at 28,000 EOH. Unit approaching major overhaul interval. Extended inspection scope performed.", "findings": "Stage 1 blade creep at 87% of limit — serviceable but overhaul should not be deferred beyond 30,000 h. TBC on blades #2 and #8 spalled.", "partsReplaced": ["TBC repair on blades #2 and #8", "Stage 1 nozzle seals (×4)", "Combustion liner gaskets (×18)"], "durationHours": 216, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 28000},
        {"timestamp": "2024-08-15T06:00:00Z", "orderNumber": "WO-2024-GT03-007", "type": "Inlet Cooling System Service", "technician": "E. Chukwu", "description": "Inlet air cooling system (evaporative cooler) serviced. High ambient temperatures (45°C) in Nigeria require active cooling.", "findings": "Evaporative cooler pads fouled — replaced. Cooling effectiveness restored: inlet depression of 8°C achieved at design ambient.", "partsReplaced": ["Evaporative cooler pads (×6)", "Water distribution nozzles (×12)"], "durationHours": 10, "result": "COMPLETED", "hoursAtService": 25000},
        {"timestamp": "2023-09-10T07:00:00Z", "orderNumber": "WO-2023-GT03-006", "type": "Combustion Inspection", "technician": "Team Zeta — I. Obi", "description": "CI at 24,000 EOH. High-cycle fatigue on fuel nozzles detected. All 18 fuel nozzles replaced preventively.", "findings": "Fuel nozzle wear accelerated — attributed to frequent start-stop peaking duty cycle. All 18 nozzles replaced.", "partsReplaced": ["All fuel nozzles (×18)", "Cross-fire tubes (×3)", "Combustion liners (×4)"], "durationHours": 96, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 24000},
        {"timestamp": "2023-05-20T07:00:00Z", "orderNumber": "WO-2023-GT03-005", "type": "Major Overhaul", "technician": "Siemens Energy MRO Team", "description": "Major overhaul at 24,000 EOH. Full strip-down, blade replacement, compressor overhaul.", "findings": "Blade row 1 at expected end-of-life. Compressor stage 3 showing erosion — blades replaced. Rotor rebalanced.", "partsReplaced": ["Blade row 1 (×36)", "Compressor stage 3 blades (×28)", "All seals and gaskets", "All bearings"], "durationHours": 720, "result": "COMPLETED", "hoursAtService": 24000},
        {"timestamp": "2022-11-01T08:00:00Z", "orderNumber": "WO-2022-GT03-004", "type": "Dust Filter Replacement (Accelerated)", "technician": "O. Adeyemi", "description": "Accelerated filter replacement due to Harmattan dust season. Dust ingestion risk elevated.", "findings": "Filter loading 3× normal rate during Harmattan season. Secondary HEPA installed as additional protection.", "partsReplaced": ["All filter stages (full replacement)", "Secondary HEPA pre-filter (new)"], "durationHours": 4, "result": "COMPLETED", "hoursAtService": 20000},
    ],
    "GT-04": [
        {"timestamp": "2026-03-11T08:15:00Z", "orderNumber": "WO-2026-GT04-012", "type": "CRITICAL: Emergency Shutdown Investigation", "technician": "Emergency Response Team", "description": "CRITICAL: Bearing #2 vibration at 7.2 mm/s. Controlled shutdown initiated. Emergency borescope of bearing compartment and hot section ordered.", "findings": "Bearing #2 shows severe oil film failure — metal pickup on shaft journal. Hot section TBC severely degraded. Unit requires immediate full overhaul.", "partsReplaced": ["PENDING — unit in emergency shutdown"], "durationHours": 8, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 31200},
        {"timestamp": "2025-11-02T09:00:00Z", "orderNumber": "WO-2025-GT04-011", "type": "Fuel Nozzle Replacement (#4)", "technician": "Y. Tanaka", "description": "Fuel nozzle #4 replaced due to carbon buildup causing combustion instability detected by dynamic pressure sensors.", "findings": "Carbon deposit on nozzle #4 tip causing combustion oscillations (35 Hz). Replaced and re-tuned combustion.", "partsReplaced": ["Fuel nozzle #4 tip assembly"], "durationHours": 8, "result": "COMPLETED", "hoursAtService": 30500},
        {"timestamp": "2025-08-14T07:00:00Z", "orderNumber": "WO-2025-GT04-010", "type": "Compressor Blade Tip Rub Repair", "technician": "Siemens Emergency MRO — K. Suzuki", "description": "Compressor blade tip rub event caused by rotor thermal bow at startup. Stage 3 blade tips rub-stripped. In-situ repair performed.", "findings": "Stage 3 compressor blade tips rubbed on casing during thermal bow. In-situ tip re-coating performed.", "partsReplaced": ["Stage 3 compressor blade tip coatings (in-situ)"], "durationHours": 48, "result": "COMPLETED", "hoursAtService": 29800},
        {"timestamp": "2025-04-10T07:00:00Z", "orderNumber": "WO-2025-GT04-009", "type": "Hot Gas Path Inspection", "technician": "Team Alpha — H. Nakamura", "description": "HGP inspection at 30,000 EOH. Unit past recommended major overhaul interval. Grid demand constraints prevented scheduled outage.", "findings": "Stage 1 blades at 112% of creep limit — overhauled blades in-situ where possible. Overhaul DEFERRED — grid operator notification issued.", "partsReplaced": ["Stage 1 nozzle segments (×4)", "Combustion liners (×16)", "Transition pieces (×4)"], "durationHours": 288, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 30000},
        {"timestamp": "2024-08-20T08:00:00Z", "orderNumber": "WO-2024-GT04-008", "type": "Bearing #2 Vibration Investigation", "technician": "R. Yamamoto", "description": "Elevated vibration on bearing #2 (3.8 mm/s) investigated. Oil sample analysis and vibration spectrum analysis performed.", "findings": "Early signs of bearing wear — oil analysis shows slight iron increase. Acceptable for continued operation with weekly monitoring.", "partsReplaced": ["Lube oil (partial drain and refill)", "Oil filter cartridge"], "durationHours": 8, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 28000},
        {"timestamp": "2022-01-10T07:00:00Z", "orderNumber": "WO-2022-GT04-006", "type": "Major Overhaul", "technician": "Siemens Energy MRO Team", "description": "Major overhaul at 24,000 EOH. All hot-section components replaced. Compressor fully inspected and cleaned.", "findings": "Blade row 1 and 2 replaced as planned. Compressor in good condition. Rotor balance within ISO 2.5.", "partsReplaced": ["Blade rows 1 and 2", "All combustion liners and nozzles", "All seals, gaskets and bearings"], "durationHours": 480, "result": "COMPLETED", "hoursAtService": 24000},
    ],
    "GT-05": [
        {"timestamp": "2025-11-15T07:00:00Z", "orderNumber": "WO-2025-GT05-006", "type": "Combustion Inspection", "technician": "Team Alpha — L. García", "description": "Scheduled CI at 6,000 EOH. Fuel nozzles inspected and cleaned, combustion liners measured, cross-fire tubes verified.", "findings": "All combustion components within tolerance. Liner wear at 8%. Excellent condition for a mid-life unit.", "partsReplaced": ["Fuel nozzle tip strainers (×16)", "Igniter plugs (×4)"], "durationHours": 72, "result": "COMPLETED", "hoursAtService": 6000},
        {"timestamp": "2025-04-10T08:00:00Z", "orderNumber": "WO-2025-GT05-005", "type": "Compressor Online Water Wash (×6)", "technician": "M. Rodriguez", "description": "Six consecutive online compressor washes per 500-EOH schedule. Compressor efficiency maintained at 96.8% of design.", "findings": "Compressor efficiency trend stable. No offline wash required this period.", "partsReplaced": [], "durationHours": 6, "result": "COMPLETED", "hoursAtService": 5800},
        {"timestamp": "2024-10-20T08:00:00Z", "orderNumber": "WO-2024-GT05-004", "type": "Lube Oil Analysis & Partial Change", "technician": "A. Sánchez", "description": "Lube oil sample analysis at 4,000 h interval. Oil condition good — partial change and filter replacement.", "findings": "Oil viscosity 31.8 cSt within spec. Acid number nominal. Trace iron particles below alarm threshold.", "partsReplaced": ["Oil filter cartridges (×3)", "ISO VG 32 oil top-up (×120 L)"], "durationHours": 10, "result": "COMPLETED", "hoursAtService": 4000},
        {"timestamp": "2024-05-15T07:00:00Z", "orderNumber": "WO-2024-GT05-003", "type": "Borescope Inspection (Routine)", "technician": "P. Martín", "description": "Routine borescope inspection per annual schedule. All compressor stages and first two turbine stages inspected.", "findings": "All stages in excellent condition. No erosion, corrosion, or FOD damage found. Hot section TBC intact.", "partsReplaced": [], "durationHours": 12, "result": "COMPLETED", "hoursAtService": 2800},
        {"timestamp": "2023-11-20T09:00:00Z", "orderNumber": "WO-2023-GT05-002", "type": "DLE Burner Replacement", "technician": "Team Beta — R. Fernández", "description": "DLE burner replacement at 6,000 h per OEM schedule. All 16 burners replaced as a complete set.", "findings": "Previous burners at scheduled replacement interval. New burners installed and combustion dynamics verified.", "partsReplaced": ["DLE burners (×16 complete assemblies)"], "durationHours": 48, "result": "COMPLETED", "hoursAtService": 500},
        {"timestamp": "2023-06-01T06:00:00Z", "orderNumber": "WO-2023-GT05-001", "type": "Commissioning & Initial Run", "technician": "Siemens Energy Commissioning Team", "description": "Unit commissioned at Plant Eta. Grid synchronisation achieved. Load ramp to 100% rated power.", "findings": "No commissioning defects. Electrical output 292 MW at rated conditions. NOx 24 ppm.", "partsReplaced": [], "durationHours": 200, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "GT-06": [
        {"timestamp": "2026-01-20T10:00:00Z", "orderNumber": "WO-2026-GT06-008", "type": "Unplanned: Exhaust Temp & Vibration Check", "technician": "Emergency Team — T. Miller", "description": "UNPLANNED: Simultaneous exhaust temp (603°C) and vibration (4.0 mm/s) elevation. Unit load reduced to 75%.", "findings": "Combustion hot spot on can #7 — liner burn-through developing. Bearing #4 journal showing wear. Maintenance within 72 h mandatory.", "partsReplaced": [], "durationHours": 6, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 19200},
        {"timestamp": "2025-06-18T07:00:00Z", "orderNumber": "WO-2025-GT06-007", "type": "Combustion Inspection", "technician": "Team Theta — C. Wilson", "description": "CI at 16,800 EOH. Fuel nozzles cleaned, liners inspected. DLE combustion system recalibrated.", "findings": "Combustion dynamics improved after recalibration. All liners within 20% wear limit.", "partsReplaced": ["Fuel nozzle strainers (×16)", "Combustion can gaskets (×16)"], "durationHours": 68, "result": "COMPLETED", "hoursAtService": 16800},
        {"timestamp": "2024-09-10T08:00:00Z", "orderNumber": "WO-2024-GT06-006", "type": "Hot Gas Path Inspection", "technician": "Team Alpha", "description": "HGP inspection at 16,000 EOH. Stage 1 blade leading-edge erosion within limits. TBC in good condition. Bearing #4 trending.", "findings": "Bearing #4 vibration at 2.8 mm/s — above 2.5 mm/s warning. Monitoring increased to weekly.", "partsReplaced": ["Stage 1 shroud seal strips (×4)", "Combustion liner gaskets (×16)"], "durationHours": 160, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 16000},
        {"timestamp": "2023-08-15T07:00:00Z", "orderNumber": "WO-2023-GT06-005", "type": "Bearing #4 Journal Remetalling", "technician": "D. Anderson", "description": "Bearing #4 journal bearing remetalled following elevated vibration trend. Journal inspected and shaft surface polished.", "findings": "White metal bearing material showing fatigue cracks — bearing remetalled. Vibration returned to 1.6 mm/s.", "partsReplaced": ["Bearing #4 journal shell (×2)"], "durationHours": 36, "result": "COMPLETED", "hoursAtService": 14500},
        {"timestamp": "2022-06-10T07:00:00Z", "orderNumber": "WO-2022-GT06-004", "type": "Combustion Inspection", "technician": "Team Beta", "description": "CI at 12,000 EOH. Normal wear found.", "findings": "All combustion components serviceable. Liner wear at 13% — acceptable.", "partsReplaced": ["Fuel nozzle tip inserts (×16)", "Cross-fire tubes (×4)"], "durationHours": 64, "result": "COMPLETED", "hoursAtService": 12000},
        {"timestamp": "2021-08-20T07:00:00Z", "orderNumber": "WO-2021-GT06-003", "type": "Major Overhaul", "technician": "Siemens Energy MRO Team", "description": "First major overhaul at 12,000 EOH. All blades inspected and re-coated. Compressor fully cleaned.", "findings": "All blades within limits — re-coated with new TBC. Compressor efficiency improved by 2.1% post-overhaul.", "partsReplaced": ["All blade TBC coatings", "Stage 1 combustion liners", "All main bearings"], "durationHours": 480, "result": "COMPLETED", "hoursAtService": 12000},
    ],
    "GT-07": [
        {"timestamp": "2025-08-12T07:00:00Z", "orderNumber": "WO-2025-GT07-006", "type": "Hot Gas Path Inspection", "technician": "Team Iota — A. Al-Mansouri", "description": "HGP inspection at 8,000 EOH. Unit in excellent condition.", "findings": "Stage 1 blade leading edges show minimal erosion. TBC intact. No corrective action required.", "partsReplaced": ["Combustion liner gaskets", "Turbine stage 1 sealing strips"], "durationHours": 120, "result": "COMPLETED", "hoursAtService": 8000},
        {"timestamp": "2024-12-20T08:00:00Z", "orderNumber": "WO-2024-GT07-005", "type": "Lube Oil Analysis & Change", "technician": "F. Al-Hashemi", "description": "Annual lube oil change. High-temperature desert environment operation.", "findings": "Oil viscosity 30.9 cSt — within ISO VG 32 spec. Acid number 0.12 (limit 0.20). No contamination.", "partsReplaced": ["ISO VG 32 turbine oil (×240 L)", "Oil filter elements (×2)"], "durationHours": 12, "result": "COMPLETED", "hoursAtService": 9500},
        {"timestamp": "2024-05-18T07:00:00Z", "orderNumber": "WO-2024-GT07-004", "type": "Combustion Inspection", "technician": "Team Kappa — M. Al-Saadi", "description": "CI at 8,000 EOH. Pipeline gas quality excellent — minimal nozzle deposits.", "findings": "Combustion system in excellent condition. No defects found. Liner wear 6%.", "partsReplaced": ["Fuel nozzle strainers (×12)", "Cross-fire tube connectors (×2)"], "durationHours": 60, "result": "COMPLETED", "hoursAtService": 8000},
        {"timestamp": "2022-12-10T07:00:00Z", "orderNumber": "WO-2022-GT07-002", "type": "Combustion Inspection", "technician": "B. Al-Rashidi", "description": "CI at 4,000 EOH. First major inspection since commissioning. Unit in excellent condition.", "findings": "Outstanding condition — no defects. Combustion efficiency high. All parameters nominal.", "partsReplaced": ["Fuel nozzle tip inserts (×12)", "Igniter plugs (×2)"], "durationHours": 56, "result": "COMPLETED", "hoursAtService": 4000},
        {"timestamp": "2021-10-05T06:00:00Z", "orderNumber": "WO-2021-GT07-001", "type": "Commissioning", "technician": "Siemens Energy Commissioning Team", "description": "Unit commissioned for gas pipeline compression duty. Speed control verified at 7,700 RPM.", "findings": "Commissioning completed. No issues found. Customer acceptance test passed.", "partsReplaced": [], "durationHours": 168, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "GT-08": [
        {"timestamp": "2025-12-01T08:00:00Z", "orderNumber": "WO-2025-GT08-006", "type": "Compressor Offline Water Wash", "technician": "C. Lim", "description": "Offline water wash performed. Tropical high-humidity environment causes compressor fouling.", "findings": "Compressor efficiency: pre-wash 86.8%, post-wash 88.3%. Improvement of 1.5% achieved.", "partsReplaced": [], "durationHours": 10, "result": "COMPLETED", "hoursAtService": 7500},
        {"timestamp": "2025-06-10T07:00:00Z", "orderNumber": "WO-2025-GT08-005", "type": "Combustion Inspection", "technician": "Team Kappa — S. Tan", "description": "CI at 4,000 EOH. High-humidity tropics cause accelerated nozzle wear.", "findings": "Fuel nozzle tips show 20% more wear than expected — tropical fuel gas moisture content implicated. Nozzles replaced.", "partsReplaced": ["All fuel nozzle tip assemblies (×12)", "Cross-fire tubes (×2)", "Combustion liner gaskets (×12)"], "durationHours": 76, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 4000},
        {"timestamp": "2024-05-15T07:00:00Z", "orderNumber": "WO-2024-GT08-004", "type": "Inlet Filtration System Upgrade", "technician": "Modifications Team", "description": "Coalescing pre-filter and HEPA filter system upgraded. Moisture separator added.", "findings": "New filtration system reduces compressor fouling rate by estimated 40%.", "partsReplaced": ["Coalescing pre-filters (×8 upgraded)", "HEPA filter banks (×4 new design)", "Moisture separator (new install)"], "durationHours": 32, "result": "COMPLETED", "hoursAtService": 2000},
        {"timestamp": "2023-03-15T06:00:00Z", "orderNumber": "WO-2023-GT08-001", "type": "Commissioning", "technician": "Siemens Energy Commissioning Team", "description": "Unit commissioned for CHP duty. Grid synchronization, heat recovery system verified.", "findings": "NOx 22 ppm. Heat recovery delivering 8.5 MW thermal at design steam pressure. Customer acceptance complete.", "partsReplaced": [], "durationHours": 192, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "GT-09": [
        {"timestamp": "2025-11-20T08:00:00Z", "orderNumber": "WO-2025-GT09-004", "type": "Combustion Inspection", "technician": "Team Lambda — P. Andersen", "description": "Combustion inspection at 2,800 EOH. First CI for this offshore unit.", "findings": "All combustion components in excellent new condition. Marine atmosphere not yet causing corrosion.", "partsReplaced": ["Igniter plugs (×2)", "Fuel nozzle strainers (×8)"], "durationHours": 48, "result": "COMPLETED", "hoursAtService": 2800},
        {"timestamp": "2025-05-15T07:00:00Z", "orderNumber": "WO-2025-GT09-003", "type": "Corrosion Protection Inspection", "technician": "Marine Coatings Team", "description": "Annual marine corrosion inspection. Offshore salt-spray environment.", "findings": "Minor surface corrosion on non-critical brackets — treated. No structural corrosion found.", "partsReplaced": ["Anti-corrosion sealant on 3 brackets", "Humidity absorber packs (×12)"], "durationHours": 16, "result": "COMPLETED", "hoursAtService": 2200},
        {"timestamp": "2024-06-10T06:00:00Z", "orderNumber": "WO-2024-GT09-001", "type": "Commissioning (Offshore)", "technician": "Siemens Energy Commissioning Team", "description": "Unit commissioned on offshore platform. Zone 2 hazardous area commissioning procedures followed.", "findings": "Emergency shutdown system verified. Firegas detection integration tested. Unit accepted for offshore operation.", "partsReplaced": [], "durationHours": 240, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "ST-03": [
        {"timestamp": "2025-07-30T07:00:00Z", "orderNumber": "WO-2025-ST03-006", "type": "Blade Inspection", "technician": "Team Mu — W. Lee", "description": "Turbine blade inspection at 10,000 EOH. Stages 1–3 checked for creep, erosion, and corrosion.", "findings": "Stages 1–3 blades within creep limits. Erosion shields intact. Stage 1 leading-edge erosion at 15% of acceptance limit.", "partsReplaced": ["Stage 1 erosion shield touch-ups (×8)", "HP turbine sealing strips (×6)"], "durationHours": 144, "result": "COMPLETED", "hoursAtService": 10000},
        {"timestamp": "2024-12-10T08:00:00Z", "orderNumber": "WO-2024-ST03-005", "type": "Steam Chemistry Verification", "technician": "Chemistry Team", "description": "Annual steam purity verification. IAPWS guidelines compliance verified.", "findings": "Cation conductivity 0.08 μS/cm (limit 0.15). Sodium <2 ppb. Chemistry fully compliant.", "partsReplaced": ["Ion exchange resin (partial replacement)"], "durationHours": 8, "result": "COMPLETED", "hoursAtService": 9800},
        {"timestamp": "2024-06-20T07:00:00Z", "orderNumber": "WO-2024-ST03-004", "type": "HP Stop Valve Overhaul", "technician": "Valve Team — S. Koh", "description": "HP stop valve overhauled during planned outage. Valve seat wear measured. Trip time tested.", "findings": "Valve seat wear acceptable. Packing renewed — steam leakage eliminated. Trip time 0.9 s — within 1.0 s specification.", "partsReplaced": ["HP valve packing set", "Valve seat ring (lapped)", "Valve stem seals"], "durationHours": 72, "result": "COMPLETED", "hoursAtService": 8000},
        {"timestamp": "2022-12-10T07:00:00Z", "orderNumber": "WO-2022-ST03-002", "type": "Routine Planned Outage", "technician": "Team Omega", "description": "Annual planned outage. HP and IP turbine casings opened. Blade row inspection, seal strip replacement, lube oil change.", "findings": "All blade rows in good condition. Turbine efficiency maintained at 94.2% of design.", "partsReplaced": ["All turbine seal strips", "Journal bearing inserts (×2)", "Turbine oil (×400 L)"], "durationHours": 120, "result": "COMPLETED", "hoursAtService": 5000},
        {"timestamp": "2022-05-20T06:00:00Z", "orderNumber": "WO-2022-ST03-001", "type": "Commissioning (Combined Cycle)", "technician": "Siemens Energy Commissioning Team", "description": "Unit commissioned as part of 750 MW combined cycle plant. HP steam at 165 bar / 565°C verified.", "findings": "Electrical output 248 MW — exceeds nameplate. Combined cycle plant efficiency 62.5%.", "partsReplaced": [], "durationHours": 360, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "ST-04": [
        {"timestamp": "2026-02-15T08:00:00Z", "orderNumber": "WO-2026-ST04-008", "type": "Unplanned: Steam Temp Elevation", "technician": "Emergency Team — R. Patel", "description": "UNPLANNED: Steam inlet temperature 16°C above normal (596°C vs 580°C baseline). Boiler superheat control valve deviation investigated.", "findings": "Boiler superheat control valve actuator drifting — causing 16°C steam temperature rise. Valve recalibrated. Root cause: actuator potentiometer wear.", "partsReplaced": ["Superheat control valve actuator potentiometer"], "durationHours": 8, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 22500},
        {"timestamp": "2025-09-10T07:00:00Z", "orderNumber": "WO-2025-ST04-007", "type": "Overhaul at 18,000 EOH", "technician": "Siemens Energy MRO Team", "description": "Scheduled overhaul at 18,000 EOH. All blades replaced, seals and bearings renewed. Refinery process heat integration verified.", "findings": "All blade rows replaced as planned. Bearing journals re-machined. Unit returned to service in 28 days.", "partsReplaced": ["All turbine blade rows", "All journal bearings", "All gland seals", "Backpressure valve assembly"], "durationHours": 672, "result": "COMPLETED", "hoursAtService": 18000},
        {"timestamp": "2023-08-12T08:00:00Z", "orderNumber": "WO-2023-ST04-005", "type": "Hot Section Inspection", "technician": "Team Nu — P. Desai", "description": "Hot section inspection at 14,000 EOH. Approaching 18,000 h overhaul — planning commenced.", "findings": "Stage 1 blade creep at 82% of limit — serviceable until 18,000 h overhaul. Stage 2 blades show salt corrosion — Mumbai coastal environment.", "partsReplaced": ["Stage 2 blade anti-corrosion coating (×12 blades)", "HP casing steam seals"], "durationHours": 120, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 14000},
        {"timestamp": "2021-09-10T07:00:00Z", "orderNumber": "WO-2021-ST04-003", "type": "Planned Outage Inspection", "technician": "Team Beta", "description": "Annual inspection at 8,000 EOH. Normal wear found.", "findings": "All turbine components within limits. Seal strips replaced as scheduled. Efficiency maintained.", "partsReplaced": ["Turbine seal strips (full set)", "Lube oil (×200 L)"], "durationHours": 72, "result": "COMPLETED", "hoursAtService": 8000},
    ],
    "GEN-01": [
        {"timestamp": "2025-10-15T08:00:00Z", "orderNumber": "WO-2025-GEN01-006", "type": "Hydrogen System Inspection", "technician": "Gas System Team — C. Oliveira", "description": "Annual hydrogen system inspection. Purity, pressure, and gas-tightness verified. Gas dryer and cooler performance checked.", "findings": "Hydrogen purity 99.8% — nominal. No leaks detected. Gas dryer capacity adequate. Cooler water flow nominal.", "partsReplaced": ["H2 system O-rings (×8)", "Gas dryer desiccant (×4 cartridges)"], "durationHours": 16, "result": "COMPLETED", "hoursAtService": 17500},
        {"timestamp": "2025-04-22T07:00:00Z", "orderNumber": "WO-2025-GEN01-005", "type": "Major Stator & Rotor Inspection", "technician": "Siemens Energy Generators Team", "description": "Planned major inspection at 7,200 h equivalent. Stator winding re-wedged. Rotor balance verified. Exciter diodes all replaced.", "findings": "Stator wedge looseness in 12 slots — re-wedged with epoxy. Rotor balance within ISO 2.5. PD levels reduced after re-wedging.", "partsReplaced": ["Stator slot wedges (×12)", "Exciter diodes (full set)", "Air cooler gaskets"], "durationHours": 240, "result": "COMPLETED", "hoursAtService": 7200},
        {"timestamp": "2024-09-10T08:00:00Z", "orderNumber": "WO-2024-GEN01-004", "type": "Insulation Resistance & PD Test", "technician": "Electrical Test Team", "description": "Annual insulation resistance and partial discharge testing.", "findings": "Insulation resistance 1,200 MΩ — well above 200 MΩ limit. Polarization index 2.8. No partial discharge activity detected.", "partsReplaced": [], "durationHours": 8, "result": "COMPLETED", "hoursAtService": 14500},
        {"timestamp": "2021-06-20T06:00:00Z", "orderNumber": "WO-2021-GEN01-001", "type": "Commissioning (1500 MVA Generator)", "technician": "Siemens Energy Commissioning Team", "description": "Generator commissioned. Hydrogen filling and gas purity verification, synchronization to grid, and full-load test performed.", "findings": "No commissioning defects. Output power 1,420 MW at rated conditions. Power factor 0.85 — excellent.", "partsReplaced": [], "durationHours": 480, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "GT-10": [
        {"timestamp": "2025-10-15T08:00:00Z", "orderNumber": "WO-2025-GT10-003", "type": "Filter Replacement (Early)", "technician": "M. Al-Sayyid", "description": "Inlet filters replaced at 2,000 EOH due to Khamsin dust storm season. Preventive early replacement.", "findings": "Filters 60% loaded — Khamsin season caused accelerated loading. Preventive replacement appropriate.", "partsReplaced": ["All filter stages (×12 elements)"], "durationHours": 4, "result": "COMPLETED", "hoursAtService": 2000},
        {"timestamp": "2025-04-20T07:00:00Z", "orderNumber": "WO-2025-GT10-002", "type": "Annual Inspection", "technician": "O. Khalil", "description": "Annual inspection per OEM schedule. All systems checked. Unit in excellent condition.", "findings": "Combustion system in excellent condition. Fuel Wobbe index stable — no nozzle deposits. All safety systems functional.", "partsReplaced": ["Igniter plugs (×2)", "Fuel nozzle strainers (×6)"], "durationHours": 16, "result": "COMPLETED", "hoursAtService": 1500},
        {"timestamp": "2024-05-20T06:00:00Z", "orderNumber": "WO-2024-GT10-001", "type": "Commissioning (Remote Site)", "technician": "Siemens Energy Commissioning Team", "description": "Unit commissioned for remote water treatment facility. Auto-start system verified. Island mode only.", "findings": "Auto-start tested: cold start to full load in 12 minutes — within 15 minute specification. All systems nominal.", "partsReplaced": [], "durationHours": 120, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "GT-11": [
        {"timestamp": "2025-11-25T08:00:00Z", "orderNumber": "WO-2025-GT11-004", "type": "Auto-Start System Test", "technician": "Controls Team — J. Mwangi", "description": "Monthly auto-start system test. Hospital campus requires guaranteed backup power within 10 seconds of main supply failure.", "findings": "Auto-start test: 0 to 5 kV bus restore in 8.5 seconds — within 10 second requirement. LPG switchover also tested successfully.", "partsReplaced": [], "durationHours": 4, "result": "COMPLETED", "hoursAtService": 4600},
        {"timestamp": "2025-07-10T07:00:00Z", "orderNumber": "WO-2025-GT11-003", "type": "Lube Oil Analysis", "technician": "K. Ngugi", "description": "First lube oil analysis at 2,000 EOH. Standby/intermittent operation profile checked.", "findings": "Oil in excellent condition despite mixed standby/running duty. Viscosity nominal. No contamination.", "partsReplaced": ["Oil filter elements (×2)"], "durationHours": 6, "result": "COMPLETED", "hoursAtService": 2000},
        {"timestamp": "2024-03-15T06:00:00Z", "orderNumber": "WO-2024-GT11-001", "type": "Commissioning (Hospital Campus)", "technician": "Siemens Energy Commissioning Team", "description": "Unit commissioned for hospital critical power. Dual-fuel switchover (NG to LPG) verified. Automatic load transfer tested.", "findings": "All commissioning requirements met. Dual-fuel switchover in <5 seconds. Load transfer to hospital bus seamless.", "partsReplaced": [], "durationHours": 168, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "GT-12": [
        {"timestamp": "2026-03-11T06:00:00Z", "orderNumber": "WO-2026-GT12-010", "type": "CRITICAL: Emergency Shutdown Initiated", "technician": "Emergency Team — Siemens Energy", "description": "CRITICAL: Simultaneous vibration (7.9 mm/s bearing #1) and exhaust temperature (642°C) exceedances. Emergency shutdown initiated. Grid operator notified.", "findings": "Root cause suspected: hot-section thermal fatigue distress causing stage 1 blade liberation event. Unit remains shut down pending full forensic inspection.", "partsReplaced": ["PENDING — forensic inspection in progress"], "durationHours": 12, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 29800},
        {"timestamp": "2025-11-10T07:00:00Z", "orderNumber": "WO-2025-GT12-009", "type": "Hot Gas Path Inspection (Extended)", "technician": "Team Rho — G. Mitchell", "description": "Extended HGP at 28,000 EOH — overhaul overdue (should have been at 24,000 h). Extensive inspection of all hot-section components.", "findings": "Stage 1 blades at 118% of creep limit. TBC on 6 blades spalled. Transition pieces oxidized. Major overhaul URGENTLY recommended.", "partsReplaced": ["6× stage 1 blade TBC re-coatings", "All transition pieces", "Combustion liner segments (×8)"], "durationHours": 336, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 28000},
        {"timestamp": "2024-06-20T07:00:00Z", "orderNumber": "WO-2024-GT12-008", "type": "Combustion Inspection", "technician": "Team Alpha — T. Brooks", "description": "CI at 24,000 EOH. HGP overhaul deferred per grid operator request — SERC capacity constraints.", "findings": "Fuel nozzles at replacement limit — all replaced. Combustion liners #3, #7, #12 replaced (emergency). HGP overhaul deferred.", "partsReplaced": ["All fuel nozzles (×16)", "Combustion liners #3, #7, #12 (emergency replacement)"], "durationHours": 96, "result": "COMPLETED_WITH_FINDINGS", "hoursAtService": 24000},
        {"timestamp": "2022-03-10T07:00:00Z", "orderNumber": "WO-2022-GT12-006", "type": "Major Overhaul", "technician": "Siemens Energy MRO Team", "description": "First major overhaul at 12,000 EOH. All blade rows inspected and re-coated. Compressor overhauled. Rotor balanced.", "findings": "All components within inspection criteria. Re-coated all stage 1–2 blades. Compressor efficiency improved post-overhaul.", "partsReplaced": ["All blade TBC coatings", "All main bearings", "All seal strips and gaskets"], "durationHours": 480, "result": "COMPLETED", "hoursAtService": 12000},
        {"timestamp": "2020-09-15T06:00:00Z", "orderNumber": "WO-2020-GT12-001", "type": "Commissioning (274 MW H-class)", "technician": "Siemens Energy Commissioning Team", "description": "Unit commissioned at Plant Rho for SERC grid. Load ramp from 0 to 274 MW completed. All 60 Hz systems verified.", "findings": "Commissioning completed without issues. Output 276 MW at 60 Hz — above nameplate. NOx 23 ppm.", "partsReplaced": [], "durationHours": 480, "result": "COMPLETED", "hoursAtService": 0},
    ],
    "GEN-02": [
        {"timestamp": "2025-04-22T07:00:00Z", "orderNumber": "WO-2025-GEN02-005", "type": "Major Inspection at 7,200 EOH", "technician": "Siemens Energy Generators Team", "description": "Major inspection at 7,200 EOH. Stator winding re-wedged, rotor balance verified. Exciter diodes replaced as a set.", "findings": "Stator winding in excellent condition — re-wedged as per schedule. Rotor unbalance within ISO 2.5. No PD activity.", "partsReplaced": ["Exciter diodes (full set)", "Air cooler gaskets (×6)", "Stator slot wedges (×6)"], "durationHours": 200, "result": "COMPLETED", "hoursAtService": 7200},
        {"timestamp": "2024-09-15T08:00:00Z", "orderNumber": "WO-2024-GEN02-004", "type": "Insulation & PD Testing", "technician": "Electrical Test Team", "description": "Annual insulation resistance and PD testing.", "findings": "IR: 950 MΩ (limit 200 MΩ). PI: 2.6. No PD detected. Excellent insulation condition.", "partsReplaced": [], "durationHours": 8, "result": "COMPLETED", "hoursAtService": 8500},
        {"timestamp": "2023-10-10T07:00:00Z", "orderNumber": "WO-2023-GEN02-003", "type": "Bearing & Cooling System Service", "technician": "Team Sigma — M. Dubois", "description": "Annual bearing and cooling system inspection. Air coolers and lube system checked.", "findings": "Drive-end bearing 0.45 mm/s. NDE bearing 0.51 mm/s. Air coolers clean. All systems nominal.", "partsReplaced": ["Bearing seal sets (×2)", "Air filter elements (×8)"], "durationHours": 20, "result": "COMPLETED", "hoursAtService": 7000},
        {"timestamp": "2021-02-10T06:00:00Z", "orderNumber": "WO-2021-GEN02-001", "type": "Commissioning (130 MVA Generator)", "technician": "Siemens Energy Commissioning Team", "description": "Air-cooled generator commissioned at Plant Sigma. Synchronization to 50 Hz grid. Full-load test at 121 MW.", "findings": "No commissioning defects. Power factor 0.85 achieved. THD <2% — excellent power quality.", "partsReplaced": [], "durationHours": 240, "result": "COMPLETED", "hoursAtService": 0},
    ],
}


def _build_cors_headers(event: dict) -> dict:
    """Return CORS headers. Echoes the request Origin if present."""
    origin = (event.get("headers") or {}).get("origin", "*")
    return {
        "Access-Control-Allow-Origin": origin,
        "Access-Control-Allow-Methods": "GET, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Authorization",
    }


def _error(status: int, message: str, headers: dict) -> dict:
    logger.warning("Returning error %d: %s", status, message)
    return {
        "statusCode": status,
        "headers": {**headers, "Content-Type": "application/json"},
        "body": json.dumps({"error": message}),
    }


def lambda_handler(event: dict, context) -> dict:  # noqa: ANN001
    cors_headers = _build_cors_headers(event)

    # ── Handle CORS preflight ────────────────────────────────────────────────
    method = (event.get("requestContext", {}).get("http", {}) or {}).get("method", "").upper()
    if method == "OPTIONS":
        return {"statusCode": 200, "headers": cors_headers, "body": ""}

    # ── Parse equipment_id query parameter ───────────────────────────────────
    params = event.get("queryStringParameters") or {}
    equipment_id = (params.get("equipment_id") or "").strip()

    if not equipment_id:
        return _error(400, "Missing 'equipment_id' query parameter.", cors_headers)

    logger.info("Maintenance history requested for: %s", equipment_id)

    history = HISTORY.get(equipment_id)
    if history is None:
        return _error(404, f"No maintenance history found for equipment '{equipment_id}'.", cors_headers)

    payload = {
        "equipmentId": equipment_id,
        "count": len(history),
        "records": history,
    }

    return {
        "statusCode": 200,
        "headers": {**cors_headers, "Content-Type": "application/json"},
        "body": json.dumps(payload, ensure_ascii=False),
    }
